spring.application.name=achou-api

spring.config.name=achou-api
spring.config.activate.on-profile=${SPRING_PROFILES_ACTIVE:default}
spring.jpa.hibernate.ddl-auto=validate
server.port=8080

logging.level.root=INFO