package com.dev.v1.achou_api.model.enums;

public enum Category {
    IT_AND_DEVELOPMENT,
    MARKETING_AND_DESIGN,
    RENOVATION_AND_CONSTRUCTION,
    MAINTENANCE_AND_REPAIRS,
    CLEANING_AND_HOUSEHOLD_SERVICES,
    HEALTH_AND_WELLNESS,
    EDUCATION_AND_CLASSES,
    CONSULTING_AND_MANAGEMENT,
    LEGAL_AND_ACCOUNTING,
    LOGISTICS_AND_TRANSPORT,
    EVENTS_AND_ENTERTAINMENT,
    OTHER
}
